# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source the first argument of include IFF it exists.
include () {
    [[ -f "$1" ]] && source "$1"
}

export SMKLEINRC_PATH=~/smkleinrc
export GITHUB_PATH=~/repos

# Default path for rust Cargo installs
export PATH=$PATH:~/.cargo/bin

# XXX XXX XXX XXX INCLUDE OTHER RC FILES HERE XXX XXX XXX XXX
# This .bashrc file should be computer-agnostic!
include ${SMKLEINRC_PATH}/bash/setuprc

if [ "$(uname)" == "Darwin" ]; then
  # Do something under Mac OS X platform
  include ${SMKLEINRC_PATH}/bash/macrc    # Full of mac-specific things
fi

# Local, should not be committed.
include ~/.googlerc
include ~/.pathrc
# XXX XXX XXX XXX END INCLUDE OTHER RC FILES XXX XXX XXX XXX

export FUCHSIA_ROOT=~/fuchsia
function fuchsia() {
  source $FUCHSIA_ROOT/scripts/env.sh && envprompt && fgo && fset x86-64 "$@"
}

source ${SMKLEINRC_PATH}/git/git-completion.bash
export PATH=${GITHUB_PATH}/depot_tools:"$PATH"

alias tmux='tmux -2'

alias bashrc='source ~/.bashrc'

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000000
HISTFILESIZE=1000000
shopt -s histappend
shopt -s cmdhist
HISTCONTROL=ignoredups
export HISTIGNORE="&:ls:[bf]g:exit"

# ZSH like tab completion
# XXX Disabled at the moment, because it was pissing me off
#bind 'set show-all-if-ambiguous on'
#bind 'TAB:menu-complete'

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
      # We have color support; assume it's compliant with Ecma-48
      # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
      # a case would tend to support setf rather than setaf.)
      color_prompt=yes
        else
      color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

stty -ixon

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

function boop {
  echo -en '\a'
  sleep 0.2
  echo -en '\a'
  sleep 0.2
  echo -en '\a'
  sleep 0.2
  echo -en '\a'
  sleep 0.2
  echo -en '\a'
}

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Used by PS1 Prompt
reset="\[\033[0m\]";
blue="\[\033[38;5;39m\]";
cyan="\[\033[38;5;38m\]";
green="\[\033[38;5;46m\]";
purple="\[\033[38;5;134m\]";
red="\[\033[38;5;196m\]";
yellow="\[\033[38;5;227m\]";
white="\[\033[38;5;250m\]";

# TODO updateme:
# .tar.gz or .tgz --> tar -xvzf
# .tar.bz2 or .tbz --> tar -xvjf
# "dtrx" --> "do the right extraction?"
alias untar='tar -xvzf'

function parse_git_dirty {
  [[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

function get_git_prompt {
  if git rev-parse --git-dir > /dev/null 2>&1; then
    top=`git rev-parse --show-toplevel`
    bn=`basename $top`
    fullremote=`git remote -v`
    shortremote=`echo ${fullremote##*/} | cut -d "." -f1 | cut -d " " -f1`
    branch=$(parse_git_branch)
    echo "${cyan}[${purple}"$shortremote"${cyan} | ${purple}"$branch"${cyan}]"
  fi
}

# Old PS1
#PS1='\[\e[0;35m\]$(get_git_prompt)\[\e[m\] \[\e[0;34m\]\w\[\e[m\] \[\e[0;32m\]\$\[\e[m\] \[\e[0;37m\]'

# Preamble
set_bash_prompt() {
  PS1="\[\033]0;\w\007\]";
  PS1+="$(get_git_prompt) "; # username
  PS1+="${green}\w "; # working directory
  PS1+="${cyan}\$ ${reset}"; # `$` (and reset color)
}
PROMPT_COMMAND=set_bash_prompt

# COLORS! YAY!
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# Shorthand for useful commands
alias helpme='echo -e "GUIDE: ${CYAN}Tool, ${GREEN}command, ${BLUE}required args, ${PURPLE}opt args${NC}...
    ${CYAN}Git${NC} Commands:
        ${CYAN}git${NC} ${GREEN}cl lint${NC} -- ${RED}Lint your CL${NC}
        ${CYAN}git${NC} ${GREEN}cl try${NC} -- ${RED}Use trybot on CL${NC}
        ${CYAN}git${NC} ${GREEN}cl upload${NC} -- ${RED}Upload your CL${NC}
        ${CYAN}git${NC} ${GREEN}cl help ${PURPLE}<command>${NC} -- ${RED}Get more git cl help${NC}
        ${CYAN}git${NC} ${GREEN}pull origin${NC} -- ${RED}Pull new changes to master${NC}
        ${GREEN}gclient sync${NC} -- ${RED}Update deps${NC}
        ${CYAN}git${NC} ${GREEN}rebase-update${NC} -- ${RED}Pull new changes to all branches.${NC}
        ${CYAN}git${NC} ${GREEN}nb/tb ${BLUE}<branch_name>${NC} -- ${RED}Create new
               branch/CL from origin/master. (tb -- current)${NC}
               Commit as much as you want to this branch. Upload to post for
               code review. Checkout base branch (either master or CL1, if new
               CL will depend on CL1) and use the ${PURPLE}--upstream_current
               ${NC}argument, which is default origin/master.
        ${CYAN}git${NC} ${GREEN}map${NC} -- ${RED}View map of commits${NC}
        ${CYAN}git${NC} ${GREEN}map-branches${NC} -- ${RED}View map of branches${NC}
        ${CYAN}git${NC} ${GREEN}grep stringpattern -- "filepattern"${NC}
    ${CYAN}Macros:${NC}
        ${CYAN}nvs ${BLUE}<number>${NC} -- ${RED}Set NACLVERBOSITY level${NC}
    ${CYAN}Shortcuts:${NC}
        ${CYAN}ff / gff / gcm / gdf${NC}
"'

# Find filename
alias ff='find . | grep'
alias gff='git ls-files | grep'
alias gs='git status'
alias gmp='git map-branches'

alias filesize='stat --printf="%s"'

function md5() {
  echo `md5sum $1 | awk '{ print $1 }'`
}

# TODO(smklein): Move these "help" commands to a new
# file someday...

BLUE_PLUS="${BLUE}+${CYAN}"
# Tmux commands
alias tmuxgood='echo -e "Pfx: Control-a
${PURPLE}META${NC}
  ${CYAN}Pfx ${BLUE_PLUS} y${NC}: Reload tmux config
  ${CYAN}Pfx ${BLUE_PLUS} s${NC}: Save tmux windows
  ${CYAN}Pfx ${BLUE_PLUS} r${NC}: Reload tmux windows
${PURPLE}WINDOWS${NC}
  ${CYAN}Pfx ${BLUE_PLUS} c${NC}: Make new window
  ${CYAN}Pfx ${BLUE_PLUS} ,${NC}: Rename window
  ${CYAN}Pfx ${BLUE_PLUS} ${ORANGE}#${NC}: Go to the window number #
  ${CYAN}Pfx ${BLUE_PLUS} w${NC}: List windows, select a window
  ${CYAN}Pfx ${BLUE_PLUS} n/p${NC}: Next / Previous window
  ${CYAN}Pfx ${BLUE_PLUS} d${NC}: Close pane / window
  ${CYAN}Pfx ${BLUE_PLUS} !${NC}: Break current pane into new window
  ${CYAN}Pfx ${BLUE_PLUS} :swap-window -s ${ORANGE}#${CYAN} -t ${ORANGE}#${NC}: Swap windows by number.
${PURPLE}PANES${NC}
  ${CYAN}Pfx ${BLUE_PLUS} e${NC}: New Pane (right)
  ${CYAN}Pfx ${BLUE_PLUS} E${NC}: Make new pane fit your dual monitor setup (requires 375 cols)
  ${CYAN}Pfx ${BLUE_PLUS} s${NC}: New Pane (down)
  ${CYAN}Pfx ${BLUE}(HOLD)${CYAN} ${BLUE_PLUS} Arrow Key${NC}: Resize pane
  ${CYAN}Pfx ${BLUE_PLUS} z${NC}: Toggle full screen
  ${CYAN}Pfx ${BLUE_PLUS} q${NC}: List panes
  ${CYAN}Pfx ${BLUE_PLUS} q ${BLUE_PLUS} ${ORANGE}#${NC}: Go to pane #
  ${CYAN}Pfx ${BLUE_PLUS} { / }${NC}: Swap pane with previous / next
  ${CYAN}Pfx ${BLUE_PLUS} :swap-pane -s # -t #${NC}: Swap panes by number.
${PURPLE}COPY/PASTING${NC}
  ${CYAN}Pfx ${BLUE_PLUS} [${NC}: Enter Copy/Navigation Mode
    SPACE to select, ENTER to copy
  ${CYAN}Pfx ${BLUE_PLUS} ]${NC}: Paste
${PURPLE}OH GEEZ I NEED HELP STILL${NC}
  ${CYAN}Pfx ${BLUE_PLUS} ?${NC}: Get help
"'


# Git aliases
alias gitgood='echo -e "GIT COMMANDS:
$ ${CYAN}gupstream${NC} -- set upstream to origin/master
$ ${CYAN}gmpush${NC} -- push to remote upstream master (from this current branch)
$ ${CYAN}gerritpatch${NC} -- Upload patch for gerrit code review
$ ${CYAN}gcm${NC} -- git commit all with a message
$ ${CYAN}gam${NC} -- gcm, but amend instead of making a new commit
$ ${CYAN}gdf${NC} -- show diffs with upstream
$ ${CYAN}gsb${NC} -- select a branch
"'

function gmp() {
  git map-branches
}
function gmb() {
  git log --graph --all --decorate --simplify-by-decoration --oneline;
}
function gupstream() { git branch -u origin/master; }
function gmpush() { git push origin `git rev-parse --abbrev-ref HEAD`:master; }
function gerritpatch() {
  if [ "$#" -eq 1 ]; then
    git push origin HEAD:refs/for/$1
    return
  fi
  echo "Whomp. Try this: $ gerritpatch [Remote Branch]"
}
function gcm() { git commit -a -m "$*" ;}
function gam() { git commit -a --amend -m "$*" ;}
alias gdfno='git diff `git rev-parse @{u}` --name-only'
alias gdfns='git diff `git rev-parse @{u}` --name-status'
alias gb='git branch'
function gdf() { # Git diff file
  fileNum=0
  IFS_ORIGINAL=$IFS
  if [ "$#" -eq 1 ]; then
    IFS=$'\n'
    for f in $(gdfno)
    do
      if [ "$1" == "$fileNum" ]; then
        toplevel=$(git rev-parse --show-toplevel)
        vim "$toplevel/$f"
      fi
      fileNum=$((fileNum + 1))
    done
  fi
  if [ "$#" -eq 0 ]; then
    upstream_branch_name=$(git rev-parse --symbolic-full-name @{u})
    echo -e "${CYAN}Tracking upstream: [${PURPLE}$upstream_branch_name${CYAN}]${NC}"
    IFS=$'\n'
    for f in $(gdfns)
    do
      IFS=$' \t\n'
      fileArray=($f)
      modStatus=${fileArray[0]}
      fileName=${fileArray[1]}
      if [ "$modStatus" = "M" ]; then
        echo -e "[$fileNum] ${CYAN}$fileName${NC}"
      elif [ "$modStatus" = "A" ]; then
        echo -e "[$fileNum] ${GREEN}$fileName${NC}"
      elif [ "$modStatus" = "D" ]; then
        echo -e "[$fileNum] ${RED}$fileName${NC}"
      else
        echo -e "[$fileNum] ${PURPLE}$fileName${NC}"
      fi
      fileNum=$((fileNum + 1))
    done
  fi
  IFS=$IFS_ORIGINAL
}

function ggd() { # Git Go Downstream
  branches=()
  eval "$(git for-each-ref --shell --format='branches+=(%(refname))' refs/heads/)"
  for BRANCH in "${branches[@]}"; do
    BRANCH=$(git rev-parse --abbrev-ref --symbolic-full-name "$BRANCH")
    UPSTREAM=$(git rev-parse --abbrev-ref --symbolic-full-name "$BRANCH"@{upstream})
    CURRENT=$(git rev-parse --abbrev-ref HEAD)
    if [ "$UPSTREAM" == "$CURRENT" ]; then
      echo "ggd: $CURRENT --> $BRANCH"
      git checkout "$BRANCH"
      return 1
    fi
  done
  echo "ggd: Cannot go downstream"
  return 0
}

function gra() { # Git Rebase All
  DO_REBASE=1
  while [ $DO_REBASE -eq 1 ]; do
    git rebase
    case $? in
      0) echo "Rebase success" ;;
      *) echo "Rebase failure"; return ;;
    esac

    ggd
    DO_REBASE=$?
  done
}

function gpatch() { # Git (gerrit?) patch
  UPSTREAM="magenta"
  if [ "$#" -eq 3 ]; then
    UPSTREAM=$3
  fi

  if [ "$#" -eq 2 ]; then
    OLDBRANCH=$(git rev-parse --abbrev-ref HEAD)
    NEWBRANCH=$1
    PATCHNO=$2
    git nb $NEWBRANCH
    git branch -u $OLDBRANCH
    git rebase
    git fetch https://fuchsia.googlesource.com/$UPSTREAM $PATCHNO && git cherry-pick FETCH_HEAD
  else
    echo "gpatch BRANCHNAME PATCHNO (refs/changes/a/b/c) UPSTREAM (Default: magenta)"
  fi
}

alias fs='find . -name .git | xargs -I % git -C %/.. --no-pager grep'

alias gsbno='git branch --list'
function gsb() { # Git select branch
  branchNum=0
  IFS_ORIGINAL=$IFS
  if [ "$#" -eq 1 ]; then
    IFS=$'\n'
    for b in $(gsbno)
    do
      b=`echo $b | cut -c 3-`
      if [ "$1" == "$branchNum" ]; then
        git checkout $b
      fi
      branchNum=$((branchNum + 1))
    done
  fi
  if [ "$#" -eq 0 ]; then
    IFS=$'\n'
    for b in $(gsbno)
    do
      IFS=$'\n'
      color=${CYAN}
      if [[ ${b:0:1} == "*" ]]; then
        color=${GREEN}
      fi
      b=`echo $b | cut -c 3-`
      echo -e "[$branchNum] ${color}$b${NC}"
      branchNum=$((branchNum + 1))
    done
  fi
  IFS=$IFS_ORIGINAL
}

function goto() {
  # Forward all arguments to the python script, and save the output code.
  output=$(python ${SMKLEINRC_PATH}/scripts/goto.py "$@")
  result=$?
  if [ $result -eq 1 ]; then
    # Exit code 1 means "cd to the directory on stdout"
    eval cd "$output"
  elif [ $result -eq 2 ]; then
    # Exit code 2 means "open the link on stdout"
    google-chrome "$output"
  else
    # Anything else is just dumped to stdout, as it is informative.
    echo -e "$output"
  fi
}


# Colored manpages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

function installDirenv() {
  cd ~/
  git clone https://github.com/direnv/direnv
  cd direnv
  sudo make install
}
promptInstall direnv installDirenv

export EDITOR=vim

# Direnv
eval "$(direnv hook bash)"
